{% set version = "1.1.0" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  url: https://github.com/computational-cell-analytics/micro-sam/archive/v{{ version }}.tar.gz
  sha256: 0437894400052cb466cd2db1bbe9b7ee44751bf628869624ecfff7a6086a5076

build:
  entry_points:
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.automatic_segmentation = micro_sam.automatic_segmentation:main
    - micro_sam.benchmark_sam = micro_sam.evaluation.benchmark_datasets:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
  noarch: python
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - kornia
    - napari >=0.5
    - nifty =1.2.1=*_4
    - pooch
    - pyqt
    - python >=3.8
    - python-elf >=0.4.8
    - python-xxhash
    - pytorch
    - segment-anything
    - torchvision
    - torch_em >=0.7.1
    - tqdm
    - timm
    - zarr

test:
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape
