{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  url: https://github.com/computational-cell-analytics/micro-sam/archive/v{{ version }}.tar.gz
  sha256: 9e122b0b4078b6a2303ef4563c576b17487fdd4133ca23df548c3a7d71e97ce6

build:
  entry_points:
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.automatic_segmentation = micro_sam.automatic_segmentation:main
    - micro_sam.benchmark_sam = micro_sam.evaluation.benchmark_datasets:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
  noarch: python
  number: 1
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - kornia
    - napari >=0.5
    - nifty >=1.2.1
    - pooch
    - pyqt
    - python >={{ python_min }}
    - python-elf >=0.4.8
    - python-xxhash
    - pytorch >=2.4.0
    - segment-anything
    - torchvision
    - torch_em >=0.7.1
    - tqdm
    - timm
    # 2.18.4 shows a circular import
    # We still are not compatible with zarr 3
    - zarr <3.0,!=2.18.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape
